### ISSUE TITLE
Running example scripts

### ISSUE THREAD

**Issue by cvanelteren** [j-friedrich/OASIS#1]
Thank you for the interesting article plus opensource code. I ran into an issue running anaconda 3.6.0.
The functions module was not in the correct scope. I fixed this by adding : 

`import os.path, sys`
`sys.path.append(
    os.path.abspath(os.path.join(os.path.dirname(__file__), os.path.pardir)))`

In the top of the examples/fig1[1-6]. py. Could also be fixed by adding `__init__.py` in the parent directory and inserting with sys.

**Comment by j-friedrich** [comment]
Thanks for the comment, but that is not an issue if run from the root directory with `python example/fig1.py` as expected and described in the README.
Nevertheless adding an `__init__.py` to be flexible with regard to the directory seems worthwhile.
