### ISSUE TITLE
No module named oasis.functions

### ISSUE THREAD

**Issue by maragkgm** [j-friedrich/OASIS#10]
Dear Johannes, 

Congratulations on the OASIS algorithm! 

May I ask something please? 

I'm trying to follow the instructions and install the Python implementation in Ubuntu, but I fail. 
I have Python 2.7.14 |Anaconda custom (64-bit), with matplotlib, numpy, scipy and cython. 

I copy the output I get in the terminal, when I run the commands of the README file. 

If you have some idea on where the problem lies, it would be extremely helpful. 

Thanks, 
George

---------------- 1 --------------------------
$ python setup.py build_ext --inplace

running build_ext
building 'oasis.oasis_methods' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/oasis
gcc -pthread -B /home/maragk/programs/anaconda2/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/maragk/programs/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/home/maragk/programs/anaconda2/include/python2.7 -c oasis/oasis_methods.cpp -o build/temp.linux-x86_64-2.7/oasis/oasis_methods.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/maragk/programs/anaconda2/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816:0,
                 from /home/maragk/programs/anaconda2/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/maragk/programs/anaconda2/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from oasis/oasis_methods.cpp:559:
/home/maragk/programs/anaconda2/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
oasis/oasis_methods.cpp: In function ‘PyObject* __pyx_pf_5oasis_13oasis_methods_20constrained_oasisAR1_2oasis(PyObject*, std::vector<__pyx_t_5oasis_13oasis_methods_Pool>, __pyx_t_5oasis_13oasis_methods_DOUBLE, PyArrayObject*)’:
oasis/oasis_methods.cpp:4180:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     __pyx_t_1 = ((__pyx_v_i < (__pyx_v_P.size() - 1)) != 0);
                             ^
oasis/oasis_methods.cpp: In function ‘PyObject* __pyx_pf_5oasis_13oasis_methods_20constrained_oasisAR1_8bar(PyObject*, PyObject*, PyObject*, PyObject*, PyObject*)’:
oasis/oasis_methods.cpp:6504:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (((__pyx_cur_scope->__pyx_v_P.size() < __pyx_cur_scope->__pyx_v_optimize_g) != 0)) {
                                           ^
oasis/oasis_methods.cpp: In function ‘PyObject* __pyx_pf_5oasis_13oasis_methods_2constrained_oasisAR1(PyObject*, PyArrayObject*, __pyx_t_5oasis_13oasis_methods_DOUBLE, __pyx_t_5oasis_13oasis_methods_DOUBLE, PyBoolObject*, PyBoolObject*, int, int, int, int)’:
oasis/oasis_methods.cpp:7879:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                     ^
oasis/oasis_methods.cpp:7889:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         __pyx_t_17 = ((__pyx_v_i == (__pyx_cur_scope->__pyx_v_P.size() - 1)) != 0);
                                  ^
oasis/oasis_methods.cpp:8151:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                     ^
oasis/oasis_methods.cpp:8273:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_2 = ((__pyx_v_count < (__pyx_v_max_iter - 1)) != 0);
                                   ^
oasis/oasis_methods.cpp:8295:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                       ^
oasis/oasis_methods.cpp:8329:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                       ^
oasis/oasis_methods.cpp:8748:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                       ^
oasis/oasis_methods.cpp:9658:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_26 = ((__pyx_v_count < __pyx_v_max_iter) != 0);
                                    ^
oasis/oasis_methods.cpp:9680:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                     ^
oasis/oasis_methods.cpp:9690:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         __pyx_t_17 = ((__pyx_v_i == (__pyx_cur_scope->__pyx_v_P.size() - 1)) != 0);
                                  ^
oasis/oasis_methods.cpp:9830:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                     ^
oasis/oasis_methods.cpp:10128:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                     ^
oasis/oasis_methods.cpp:10399:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_26 = ((__pyx_v_count < (__pyx_v_max_iter - 1)) != 0);
                                    ^
oasis/oasis_methods.cpp:10421:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                       ^
oasis/oasis_methods.cpp:10455:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                       ^
oasis/oasis_methods.cpp:10943:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                       ^
oasis/oasis_methods.cpp:11579:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                   ^
oasis/oasis_methods.cpp:12555:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                   ^
oasis/oasis_methods.cpp: In function ‘PyObject* __pyx_pf_5oasis_13oasis_methods_4oasisAR2(PyObject*, PyArrayObject*, __pyx_t_5oasis_13oasis_methods_DOUBLE, __pyx_t_5oasis_13oasis_methods_DOUBLE, __pyx_t_5oasis_13oasis_methods_DOUBLE, __pyx_t_5oasis_13oasis_methods_DOUBLE, int, PyBoolObject*)’:
oasis/oasis_methods.cpp:15541:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (__pyx_t_12 = 0; __pyx_t_12 < __pyx_t_39; __pyx_t_12+=1) {
                                     ^
oasis/oasis_methods.cpp:17620:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (__pyx_t_12 = 1; __pyx_t_12 < __pyx_t_39; __pyx_t_12+=1) {
                                   ^
oasis/oasis_methods.cpp: In function ‘PyObject* __pyx_pf_5oasis_13oasis_methods_20constrained_oasisAR2_oasis(PyObject*, PyArrayObject*, std::vector<__pyx_t_5oasis_13oasis_methods_Pool>, PyArrayObject*, PyArrayObject*, PyArrayObject*, PyArrayObject*, PyArrayObject*)’:
oasis/oasis_methods.cpp:18366:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     __pyx_t_1 = ((__pyx_v_i < (__pyx_v_P.size() - 1)) != 0);
                             ^
oasis/oasis_methods.cpp:19056:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (__pyx_t_7 = 1; __pyx_t_7 < __pyx_t_29; __pyx_t_7+=1) {
                                 ^
oasis/oasis_methods.cpp: In function ‘PyObject* __pyx_pf_5oasis_13oasis_methods_6constrained_oasisAR2(PyObject*, PyArrayObject*, __pyx_t_5oasis_13oasis_methods_DOUBLE, __pyx_t_5oasis_13oasis_methods_DOUBLE, __pyx_t_5oasis_13oasis_methods_DOUBLE, PyBoolObject*, PyBoolObject*, int, int, int, int, int)’:
oasis/oasis_methods.cpp:21708:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_25 = ((__pyx_v_count < __pyx_v_max_iter) != 0);
                                    ^
oasis/oasis_methods.cpp:21779:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (__pyx_t_1 = 1; __pyx_t_1 < __pyx_t_30; __pyx_t_1+=1) {
                                     ^
oasis/oasis_methods.cpp:21798:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         __pyx_t_26 = ((__pyx_v_i == (__pyx_v_P.size() - 1)) != 0);
                                  ^
oasis/oasis_methods.cpp:21934:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         __pyx_t_25 = ((__pyx_v_i == (__pyx_v_P.size() - 2)) != 0);
                                  ^
oasis/oasis_methods.cpp:22355:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (__pyx_t_1 = 1; __pyx_t_1 < __pyx_t_30; __pyx_t_1+=1) {
                                     ^
oasis/oasis_methods.cpp:22414:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         __pyx_t_26 = ((__pyx_v_i == (__pyx_v_P.size() - 1)) != 0);
                                  ^
oasis/oasis_methods.cpp:22479:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         __pyx_t_25 = ((__pyx_v_i == (__pyx_v_P.size() - 2)) != 0);
                                  ^
oasis/oasis_methods.cpp: In function ‘PyObject* __pyx_pf_5oasis_13oasis_methods_24constrained_oasisAR1_f32_2oasis(PyObject*, std::vector<__pyx_t_5oasis_13oasis_methods_Pool32>, __pyx_t_5oasis_13oasis_methods_SINGLE, PyArrayObject*)’:
oasis/oasis_methods.cpp:27656:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     __pyx_t_1 = ((__pyx_v_i < (__pyx_v_P.size() - 1)) != 0);
                             ^
oasis/oasis_methods.cpp: In function ‘PyObject* __pyx_pf_5oasis_13oasis_methods_24constrained_oasisAR1_f32_8bar(PyObject*, PyObject*, PyObject*, PyObject*, PyObject*)’:
oasis/oasis_methods.cpp:29899:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (((__pyx_cur_scope->__pyx_v_P.size() < __pyx_cur_scope->__pyx_v_optimize_g) != 0)) {
                                           ^
oasis/oasis_methods.cpp: In function ‘PyObject* __pyx_pf_5oasis_13oasis_methods_10constrained_oasisAR1_f32(PyObject*, PyArrayObject*, __pyx_t_5oasis_13oasis_methods_SINGLE, __pyx_t_5oasis_13oasis_methods_SINGLE, PyBoolObject*, PyBoolObject*, int, int, int, int)’:
oasis/oasis_methods.cpp:31199:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                     ^
oasis/oasis_methods.cpp:31209:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         __pyx_t_17 = ((__pyx_v_i == (__pyx_cur_scope->__pyx_v_P.size() - 1)) != 0);
                                  ^
oasis/oasis_methods.cpp:31471:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                     ^
oasis/oasis_methods.cpp:31593:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_2 = ((__pyx_v_count < (__pyx_v_max_iter - 1)) != 0);
                                   ^
oasis/oasis_methods.cpp:31615:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                       ^
oasis/oasis_methods.cpp:31649:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                       ^
oasis/oasis_methods.cpp:32041:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                       ^
oasis/oasis_methods.cpp:32923:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_26 = ((__pyx_v_count < __pyx_v_max_iter) != 0);
                                    ^
oasis/oasis_methods.cpp:32945:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                     ^
oasis/oasis_methods.cpp:32955:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         __pyx_t_17 = ((__pyx_v_i == (__pyx_cur_scope->__pyx_v_P.size() - 1)) != 0);
                                  ^
oasis/oasis_methods.cpp:33095:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                     ^
oasis/oasis_methods.cpp:33393:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                     ^
oasis/oasis_methods.cpp:33664:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_26 = ((__pyx_v_count < (__pyx_v_max_iter - 1)) != 0);
                                    ^
oasis/oasis_methods.cpp:33686:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                       ^
oasis/oasis_methods.cpp:33720:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                       ^
oasis/oasis_methods.cpp:34181:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                       ^
oasis/oasis_methods.cpp:34817:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                   ^
oasis/oasis_methods.cpp:35739:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (__pyx_t_1 = 0; __pyx_t_1 < __pyx_t_21; __pyx_t_1+=1) {
                                   ^
oasis/oasis_methods.cpp: In function ‘PyObject* __pyx_pf_5oasis_13oasis_methods_4oasisAR2(PyObject*, PyArrayObject*, __pyx_t_5oasis_13oasis_methods_DOUBLE, __pyx_t_5oasis_13oasis_methods_DOUBLE, __pyx_t_5oasis_13oasis_methods_DOUBLE, __pyx_t_5oasis_13oasis_methods_DOUBLE, int, PyBoolObject*)’:
oasis/oasis_methods.cpp:17298:62: warning: ‘__pyx_v_j’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       (__pyx_v_P[__pyx_t_17]).t = ((__pyx_v_P[__pyx_t_17]).t + __pyx_v_j);
                                                              ^
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/oasis
g++ -pthread -shared -B /home/maragk/programs/anaconda2/compiler_compat -L/home/maragk/programs/anaconda2/lib -Wl,-rpath=/home/maragk/programs/anaconda2/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-2.7/oasis/oasis_methods.o -L/home/maragk/programs/anaconda2/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/oasis/oasis_methods.so
copying build/lib.linux-x86_64-2.7/oasis/oasis_methods.so -> oasis

---------------- 2 --------------------------
$ python setup.py clean --all

running clean
removing 'build/temp.linux-x86_64-2.7' (and everything under it)
removing 'build/lib.linux-x86_64-2.7' (and everything under it)
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-2.7' does not exist -- can't clean it
removing 'build'

---------------- 3 --------------------------
$ python examples/fig[1-6].py

Traceback (most recent call last):
  File "examples/fig1.py", line 7, in <module>
    from oasis.functions import gen_data
ImportError: No module named oasis.functions

**Comment by j-friedrich** [comment]
According to the cython online docs you can just ignore the deprecated NumPy API warnings. As long as there are just warnings and no errors you are most likely fine.

The examples run if you either call them with ipython instead python (I updated the readme accordingly) or if OASIS is added to your PYTHONPATH (via export PYTHONPATH=path_to_OASIS:$PYTHONPATH with path_to_OASIS being the actual path where OASIS is installed)
