### ISSUE TITLE
Testing performance

### ISSUE THREAD

**Issue by philippberens** [j-friedrich/OASIS#11]
Hi Johannes,

we encountered an issue when using OASIS. On the spikefinder data, the algorithm trains very quickly but  returns errors when performing prediction (`GpuArrayException: b'cuMemAlloc: CUDA_ERROR_OUT_OF_MEMORY: out of memory'`).  I don't think our Titan 10 Xp is likely to be running into memory problems.  Any idea of what might be going on?

Best
Philipp and @lukerogerson

**Comment by j-friedrich** [comment]
There's no GPU usage in this repo. Is memory still an issue and are you referring to this repo: https://github.com/j-friedrich/spikefinder_submission ?

**Comment by j-friedrich** [comment]
I verified that the other repo runs perfectly fine with a Quadro M4000 using tensorflow-gpu 1.4.1 and keras 2.1.3.
The issue does not refer to this repo, hence closing it.
