### ISSUE TITLE
Input to OASIS

### ISSUE THREAD

**Issue by Sabermea** [j-friedrich/OASIS#13]
I'm quite new to this field. I was wondering what data should be used as input to OASIS. Raw fluorescence measurement (F) or ΔF/F?

**Comment by j-friedrich** [comment]
The algorithm assumes a constant baseline, hence you should correct for
baseline drift before calling it and hence use ΔF/F.
The baseline can be non-zero and is by default optimized automatically.
By default the AR parameters are estimated from the autocorrelation, but if
you have a good idea of the rise and decay time of your calcium indicator,
as you likely do, it is better to provide them using the formulas from the
Demo!
<https://github.com/j-friedrich/OASIS/blob/master/examples/Demo.ipynb>
Some users reported that good results are obtained using the AR1 model,
providing a  (lower) estimate of the AR parameter (decay factor) g, and
improving upon it by setting optimize_g=5.

**Comment by Sabermea** [comment]
Thank you so much for the explanation. That makes sense. I have another question about the interpretation of the output. I'm not sure what the magnitude of spikes means. Is it the probability of spiking or just Ca intake at that particular time.

**Comment by j-friedrich** [comment]
For interpreting the output see this comment of my colleague:
https://github.com/flatironinstitute/CaImAn-MATLAB/wiki/Interpretation-of-spiking-variable-S
