### ISSUE TITLE
Using OASIS with CalmAn ouput C matrix

### ISSUE THREAD

**Issue by akatav** [j-friedrich/OASIS#15]
Hi,
I have matrix 'C' from CalmAn obtained from cnm.estimates.idx_components. I'd like to get the spike train for this matrix. How can i use oasis for this ?

**Comment by j-friedrich** [comment]
You need to call `deconvolve` (or directly one of the functions it wraps like `oasisAR1`, cf demo notebook) on every row of matrix `C`, e.g.:
`results = [deconvolve(c, penalty=1) for c in C]`

Most of oasis is actually included within CaImAn and you can run:
`cnm.estimates.deconvolve(cnm.params)`
to deconvolve `cnm.estimates.C`
and the deconvolved trace is stored as `cnm.estimates.S`
