### ISSUE TITLE
Trouble Installing

### ISSUE THREAD

**Issue by jimotis** [j-friedrich/OASIS#16]
Dear Johannes,
Thank you for all of your hard work in creating open-source ca2+ imaging analysis pipelines. 

I've been trying to use some of your deconvolution stuff through OASIS, but am having all sorts of trouble installing. First, there seems to be another OASIS, run in part by a different Johannes? I tried pip install oasis but I believe I got a different package altogether. https://github.com/ngmarchant/oasis. I can run/edit python scripts, but am terribly new to installation, so please forgive my naivety. 

I did put your files from the "oasis-master" zip file into my default directory, but am running into this error which prevents installation.  Do you know what I'm doing wrong? 

Best wishes,
Jim

Compiling oasis/oasis_methods.pyx because it changed.
[1/1] Cythonizing oasis/oasis_methods.pyx
/Users/jamesotis/opt/anaconda3/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /Users/jamesotis/Dropbox/2P Imaging Projects/Jim/Oasis/oasis/oasis_methods.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/Users/jamesotis/opt/anaconda3/lib/python3.7/distutils/fancy_getopt.py", line 233, in getopt
    opts, args = getopt.getopt(args, short_opts, self.long_opts)
  File "/Users/jamesotis/opt/anaconda3/lib/python3.7/getopt.py", line 95, in getopt
    opts, args = do_shorts(opts, args[0][1:], shortopts, args[1:])
  File "/Users/jamesotis/opt/anaconda3/lib/python3.7/getopt.py", line 195, in do_shorts
    if short_has_arg(opt, shortopts):
  File "/Users/jamesotis/opt/anaconda3/lib/python3.7/getopt.py", line 211, in short_has_arg
    raise GetoptError(_('option -%s not recognized') % opt, opt)
getopt.GetoptError: option -f not recognized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesotis/opt/anaconda3/lib/python3.7/distutils/core.py", line 134, in setup
    ok = dist.parse_command_line()
  File "/Users/jamesotis/opt/anaconda3/lib/python3.7/distutils/dist.py", line 475, in parse_command_line
    args = parser.getopt(args=self.script_args, object=self)
  File "/Users/jamesotis/opt/anaconda3/lib/python3.7/distutils/fancy_getopt.py", line 235, in getopt
    raise DistutilsArgError(msg)
distutils.errors.DistutilsArgError: option -f not recognized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesotis/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-c655e1e114d1>", line 31, in <module>
    tests_require=test_required)
  File "/Users/jamesotis/opt/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Users/jamesotis/opt/anaconda3/lib/python3.7/distutils/core.py", line 136, in setup
    raise SystemExit(gen_usage(dist.script_name) + "\nerror: %s" % msg)
SystemExit: usage: ipykernel_launcher.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: ipykernel_launcher.py --help [cmd1 cmd2 ...]
   or: ipykernel_launcher.py --help-commands
   or: ipykernel_launcher.py cmd --help

error: option -f not recognized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesotis/opt/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1151, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/Users/jamesotis/opt/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py", line 319, in wrapped
    return f(*args, **kwargs)
  File "/Users/jamesotis/opt/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py", line 353, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/Users/jamesotis/opt/anaconda3/lib/python3.7/inspect.py", line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'
---------------------------------------------------------------------------
GetoptError                               Traceback (most recent call last)
~/opt/anaconda3/lib/python3.7/distutils/fancy_getopt.py in getopt(self, args, object)
    232         try:
--> 233             opts, args = getopt.getopt(args, short_opts, self.long_opts)
    234         except getopt.error as msg:

~/opt/anaconda3/lib/python3.7/getopt.py in getopt(args, shortopts, longopts)
     94         else:
---> 95             opts, args = do_shorts(opts, args[0][1:], shortopts, args[1:])
     96 

~/opt/anaconda3/lib/python3.7/getopt.py in do_shorts(opts, optstring, shortopts, args)
    194         opt, optstring = optstring[0], optstring[1:]
--> 195         if short_has_arg(opt, shortopts):
    196             if optstring == '':

~/opt/anaconda3/lib/python3.7/getopt.py in short_has_arg(opt, shortopts)
    210             return shortopts.startswith(':', i+1)
--> 211     raise GetoptError(_('option -%s not recognized') % opt, opt)
    212 

GetoptError: option -f not recognized

During handling of the above exception, another exception occurred:

DistutilsArgError                         Traceback (most recent call last)
~/opt/anaconda3/lib/python3.7/distutils/core.py in setup(**attrs)
    133     try:
--> 134         ok = dist.parse_command_line()
    135     except DistutilsArgError as msg:

~/opt/anaconda3/lib/python3.7/distutils/dist.py in parse_command_line(self)
    474         parser.set_aliases({'licence': 'license'})
--> 475         args = parser.getopt(args=self.script_args, object=self)
    476         option_order = parser.get_option_order()

~/opt/anaconda3/lib/python3.7/distutils/fancy_getopt.py in getopt(self, args, object)
    234         except getopt.error as msg:
--> 235             raise DistutilsArgError(msg)
    236 

DistutilsArgError: option -f not recognized

During handling of the above exception, another exception occurred:

SystemExit                                Traceback (most recent call last)
~/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py in run_code(self, code_obj, result, async_)
   3330                 else:
-> 3331                     exec(code_obj, self.user_global_ns, self.user_ns)
   3332             finally:

<ipython-input-7-c655e1e114d1> in <module>
     30       install_requires=required,
---> 31       tests_require=test_required)

~/opt/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py in setup(**attrs)
    152     _install_setup_requires(attrs)
--> 153     return distutils.core.setup(**attrs)
    154 

~/opt/anaconda3/lib/python3.7/distutils/core.py in setup(**attrs)
    135     except DistutilsArgError as msg:
--> 136         raise SystemExit(gen_usage(dist.script_name) + "\nerror: %s" % msg)
    137 

SystemExit: usage: ipykernel_launcher.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: ipykernel_launcher.py --help [cmd1 cmd2 ...]
   or: ipykernel_launcher.py --help-commands
   or: ipykernel_launcher.py cmd --help

error: option -f not recognized

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
~/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py in run_code(self, code_obj, result, async_)
   3336             if result is not None:
   3337                 result.error_in_exec = e
-> 3338             self.showtraceback(exception_only=True)
   3339             warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
   3340         except self.custom_exceptions:

~/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py in showtraceback(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)
   2036                            'the full traceback.\n']
   2037                     stb.extend(self.InteractiveTB.get_exception_only(etype,
-> 2038                                                                      value))
   2039                 else:
   2040                     try:

~/opt/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py in get_exception_only(self, etype, value)
    824         value : exception value
    825         """
--> 826         return ListTB.structured_traceback(self, etype, value)
    827 
    828     def show_exception_only(self, etype, evalue):

~/opt/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, evalue, etb, tb_offset, context)
    703                     chained_exceptions_tb_offset, context)
    704                 + chained_exception_message
--> 705                 + out_list)
    706 
    707         return out_list

~/opt/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1416             self.tb = tb
   1417         return FormattedTB.structured_traceback(
-> 1418             self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1419 
   1420 

~/opt/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1316             # Verbose modes need a full traceback
   1317             return VerboseTB.structured_traceback(
-> 1318                 self, etype, value, tb, tb_offset, number_of_lines_of_context
   1319             )
   1320         elif mode == 'Minimal':

~/opt/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
   1184         exception = self.get_parts_of_chained_exception(evalue)
   1185         if exception:
-> 1186             formatted_exceptions += self.prepare_chained_exception_message(evalue.__cause__)
   1187             etype, evalue, etb = exception
   1188         else:

TypeError: can only concatenate str (not "list") to str

**Comment by j-friedrich** [comment]
To get rid of the language warning you can add the language level to `setup.py` by changing the `compiler_directives` in line 28 to `{cdivision: True, 'language_level': "3"}`.

The issue seems to be elsewhere though. What versions of python, cython and setuptools do you have installed?

Another option is to get OASIS to run in a separate environment, using the following:
```
conda create -n oasis python=3.7
conda activate oasis
conda install cython numpy scipy matplotlib
python setup.py build_ext -i
```

**Comment by jimotis** [comment]
Thank you for your very helpful response, I think it's almost installed. Just one issue:

I created a separate env using the code you provided in terminal. However, when I run "python setup.py build_ext -i", I get a directory error "python: can't open file 'setup.py': [Errno 2] No such file or directory". I tried adding setup.py from your GitHub zip to the oasis env. folder (or subfolders) but I get the same error. Could I use pip install instead at this point? 

Thanks again for your help. Below is version info you were asking about in case you need it.
Best,
Jim 


Cython: 0.29.21 (oasis env) and 0.29.15 (regular)
Python: 3.7.9 (oasis env) and 3.7.6 (regular)

Would "pip" be setuptools? If so, this is the info for pip: 
Regular -- "pip 20.3.3 from /Users/jamesotis/opt/anaconda3/lib/python3.7/site-packages/pip (python 3.7)"
Env --"pip 20.3.3 from /Users/jamesotis/opt/anaconda3/envs/oasis/lib/python3.7/site-packages/pip (python 3.7)"

**Comment by j-friedrich** [comment]
OASIS is not set up to be installed via pip. You need to either clone the repo or download it, as you seem to have done, and run the last line `python setup.py build_ext -i` in the directory OASIS-master where setup.py is located.

**Comment by jimotis** [comment]
Done. The last issue I had was using Jupyter in the oasis environment, but this helped in case any other newbies need the extra instruction: http://echrislynch.com/2019/02/01/adding-an-environment-to-jupyter-notebooks/. I also didn't realize that path.append('../') meant that you need to put the oasis directory in the (...), I'm sure another rookie mistake.

Looks like it's working now. THANK YOU!!!
