### ISSUE TITLE
refactoring into a package

### ISSUE THREAD

**Issue by neuromusic** [j-friedrich/OASIS#2]
it would facilitate installation to build this into a python package so that setup.py handles installing the package to site-packages.

would you be interested in a PR to add this functionality?

**Comment by j-friedrich** [comment]
Hi Justin,
would appreciate the PR, if it packages things more nicely and facilitates installation. Wrote the setup.py merely for cythonizing, thus it even lacks the basic stuff like version, description, author, license ... that I should add.
