### ISSUE TITLE
Install error - 'g++-10' failed with exit status 1

### ISSUE THREAD

**Issue by XiaoqianSun0104** [j-friedrich/OASIS#22]
Hi,

I tried to install oasis by running setup.py and ran into this error:
unable to execute 'g++-10': No such file or directory
error: command 'g++-10' failed with exit status 1

Please see the attached screenshot for more info:
![image](https://user-images.githubusercontent.com/31903092/153787464-250b79e9-b938-4e37-aa53-a1b2c1f05849.png)

Can you please take a look and help me out? Thank you.

**Comment by XiaoqianSun0104** [comment]
I solved this question by changing 'g++-10' in os.environ["CC"] = "g++-10"/os.environ["CXX"] = "g++-10" to 'gcc'. Some functions were not set up successfully, but just copied __init__.py and functions.py to anaconda3/lib/python3.8/site-packages/oasis folder and I was able to import Oasis in python.

**Comment by j-friedrich** [comment]
Thanks, fixed it. I had accidentally accepted a PR that introduced those unnecessary lines setting environmental variables.
