### ISSUE TITLE
make OASIS available on PyPI?

### ISSUE THREAD

**Issue by sg-s** [j-friedrich/OASIS#23]
hi, it'd be great to be able to:

```bash
pip install oasis-deconv
```

do you have plans for doing this, alternately, may i put this on the PyPI and link back to this repo?

**Comment by j-friedrich** [comment]
Hi @sg-s,
I finally deployed the package to PyPI. You should now be able to do:
```
pip install oasis-deconv
```
It works for me, please let me know if it works for you too. 

* I put some wheels for MacOS on PyPI. 
* On Linux I'd like to compile wheels on an older toolchain than I have available right now, but building from source distribution should be fine on Linux anyways.
* It would probably be good to have wheels for Windows, where compilation is typically most cumbersome. I don't have quick&simple access to Windows right now, but might add those wheels later.

**Comment by sg-s** [comment]
awesome, thank you so much! i'll try out next week (out sick now)

**Comment by j-friedrich** [comment]
Oh no, hope you get well soon!
