### ISSUE TITLE
Remove the penalty?

### ISSUE THREAD

**Issue by javierhow** [j-friedrich/OASIS#24]
Hi,

Nice code. I'd like to not use a penalty when deconvolving - is this possible? It looks like I have to choose between L0 or L1; the MATLAB version, on the other hand, seems like it might allow one to not use a penalty.

Thanks,
Javier

**Comment by j-friedrich** [comment]
Yes, if you call `oasisAR1` with the default paramters (`lam=0`, `s_min=0`), then no sparsity is imposed. Note that you need to remove the baseline and provide the AR parameter (decay time constant), see e.g. cell 8 in the [demo](https://github.com/j-friedrich/OASIS/blob/master/examples/Demo.ipynb)
The `deconvolve` method estimates those automatically from the data, but if you have a good idea about the time constant of your indicator, it's often better to provide it (and optionally further optimize it by setting `optimize_g`, c.f. cell 10.

**Comment by javierhow** [comment]
Thanks! That worked.  :)
