### ISSUE TITLE
trying to use a function not available in the package

### ISSUE THREAD

**Issue by ClaudiaEF** [j-friedrich/OASIS#3]
Hi!
I encountered a problem with some of my data -- when in ' estimate time constant'  in cannot find a good model, the software crashes here:
while max(abs(roots([1,-g(:)']))>1) && p < 5
%     warning('No stable AR(%i) model found. Checking for AR(%i) model \n',options.p,options.p+1);
    p = p + 1;
    g = estimate_time_constants(y,p,sn,lags);
end
 
because it cannot find 'options', but also because estimate_time_constants is not available in the package I downloaded.
Am I doing something wrong??
Thanks

CLaudia

**Comment by j-friedrich** [comment]
Hi Claudia,

estimate_time_constants is in functions.py. However, it does not include the lines you mentioned?!
Just make sure that you are either in the root directory of the package or add it too your PYTHONPATH, so that 
from functions import estimate_time_constant
yields no ImportError.

Cheers
Johannes

**Comment by ClaudiaEF** [comment]
Hi Johannes,

Thanks Johannes.
I'm using matlab, not python -- not sure whether this is the difference.
The lines that I mention are in estimate_time_constant.m ; but the function that I don't seem to have is estimate_time_constants.m

Cheers

Claudia

**Comment by j-friedrich** [comment]
I see. I’m not using Matlab myself, but seems to be simply a typo. Try renaming estimate_time_constant.m to estimate_time_constants.m (or alternatively rename the function calls). If that doesn’t fix it, you’d need to ask Pengcheng, who wrote the Matlab version (https://github.com/zhoupc/OASIS_matlab).

**Comment by ClaudiaEF** [comment]
OK, I'll try that -- but would it be OK that the function calls itself?
THanks!

**Comment by j-friedrich** [comment]
Yes, just had a look at Pengcheng's version and the function calls indeed itself again but with an increased value of p (the order of the auto-regressive process). Apparently he didn't just translate my code, hope it works with the name change.

**Comment by ClaudiaEF** [comment]
I'll try that out, thanks!

**Comment by j-friedrich** [comment]
Closing, cause the issue relates not to this but to the Matlab version.
